USE literature;
INSERT INTO authors (
		first_name,
		last_name,
		date_of_birth,
		date_of_death,
		nationality,
		biography,
		email,
		website,
		gender,
		profile_picture
	)
VALUES (
		'John',
		'Doe',
		'1970-01-01',
		NULL,
		'American',
		'John is a well-known author...',
		'john.doe@example.com',
		'http://johndoe.com',
		'Male',
		'http://johndoe.com/pic1.jpg'
	),
	(
		'Jane',
		'Smith',
		'1980-02-15',
		NULL,
		'British',
		'Jane has written several bestsellers...',
		'jane.smith@example.com',
		'http://janesmith.com',
		'Female',
		'http://janesmith.com/pic2.jpg'
	),
	(
		'Robert',
		'Brown',
		'1965-03-25',
		'2020-08-20',
		'Canadian',
		'Robert was a prolific author...',
		'robert.brown@example.com',
		'http://robertbrown.com',
		'Male',
		'http://robertbrown.com/pic3.jpg'
	),
	(
		'Emily',
		'Johnson',
		'1990-04-10',
		NULL,
		'Australian',
		'Emily writes fiction...',
		'emily.johnson@example.com',
		'http://emilyjohnson.com',
		'Female',
		'http://emilyjohnson.com/pic4.jpg'
	),
	(
		'Michael',
		'Williams',
		'1975-05-30',
		NULL,
		'Irish',
		'Michael is known for his thrillers...',
		'michael.williams@example.com',
		'http://michaelwilliams.com',
		'Male',
		'http://michaelwilliams.com/pic5.jpg'
	),
	(
		'Sarah',
		'Jones',
		'1985-06-20',
		NULL,
		'New Zealander',
		'Sarah has a passion for writing...',
		'sarah.jones@example.com',
		'http://sarahjones.com',
		'Female',
		'http://sarahjones.com/pic6.jpg'
	),
	(
		'David',
		'Miller',
		'1972-07-15',
		NULL,
		'South African',
		'David specializes in historical novels...',
		'david.miller@example.com',
		'http://davidmiller.com',
		'Male',
		'http://davidmiller.com/pic7.jpg'
	),
	(
		'Laura',
		'Davis',
		'1995-08-05',
		NULL,
		'American',
		'Laura is a young and upcoming author...',
		'laura.davis@example.com',
		'http://lauradavis.com',
		'Female',
		'http://lauradavis.com/pic8.jpg'
	),
	(
		'James',
		'Wilson',
		'1982-09-10',
		NULL,
		'British',
		'James writes science fiction...',
		'james.wilson@example.com',
		'http://jameswilson.com',
		'Male',
		'http://jameswilson.com/pic9.jpg'
	),
	(
		'Patricia',
		'Martinez',
		'1968-10-25',
		NULL,
		'Spanish',
		'Patricia has been writing for over 20 years...',
		'patricia.martinez@example.com',
		'http://patriciamartinez.com',
		'Female',
		'http://patriciamartinez.com/pic10.jpg'
	),
	(
		'Chris',
		'Garcia',
		'1978-11-30',
		NULL,
		'Mexican',
		'Chris is known for his detective novels...',
		'chris.garcia@example.com',
		'http://chrisgarcia.com',
		'Male',
		'http://chrisgarcia.com/pic11.jpg'
	),
	(
		'Anna',
		'Martinez',
		'1983-12-15',
		NULL,
		'Spanish',
		'Anna writes romantic fiction...',
		'anna.martinez@example.com',
		'http://annamartinez.com',
		'Female',
		'http://annamartinez.com/pic12.jpg'
	),
	(
		'Daniel',
		'Rodriguez',
		'1976-01-05',
		NULL,
		'Argentinian',
		'Daniel is a famous poet...',
		'daniel.rodriguez@example.com',
		'http://danielrodriguez.com',
		'Male',
		'http://danielrodriguez.com/pic13.jpg'
	),
	(
		'Sophia',
		'Hernandez',
		'1988-02-20',
		NULL,
		'Colombian',
		'Sophia writes children\'s books...',
		'sophia.hernandez@example.com',
		'http://sophiahernandez.com',
		'Female',
		'http://sophiahernandez.com/pic14.jpg'
	),
	(
		'William',
		'Lopez',
		'1969-03-30',
		NULL,
		'Chilean',
		'William is an expert in non-fiction...',
		'william.lopez@example.com',
		'http://williamlopez.com',
		'Male',
		'http://williamlopez.com/pic15.jpg'
	),
	(
		'Mia',
		'Gonzalez',
		'1991-04-15',
		NULL,
		'Peruvian',
		'Mia is an emerging author...',
		'mia.gonzalez@example.com',
		'http://miagonzalez.com',
		'Female',
		'http://miagonzalez.com/pic16.jpg'
	),
	(
		'Alexander',
		'Moore',
		'1984-05-25',
		NULL,
		'American',
		'Alexander writes philosophical essays...',
		'alexander.moore@example.com',
		'http://alexandermoore.com',
		'Male',
		'http://alexandermoore.com/pic17.jpg'
	),
	(
		'Olivia',
		'Clark',
		'1973-06-10',
		NULL,
		'Canadian',
		'Olivia is an award-winning author...',
		'olivia.clark@example.com',
		'http://oliviaclark.com',
		'Female',
		'http://oliviaclark.com/pic18.jpg'
	),
	(
		'Benjamin',
		'Lee',
		'1986-07-30',
		NULL,
		'Australian',
		'Benjamin is known for his travel writing...',
		'benjamin.lee@example.com',
		'http://benjaminlee.com',
		'Male',
		'http://benjaminlee.com/pic19.jpg'
	),
	(
		'Emma',
		'Walker',
		'1993-08-20',
		NULL,
		'British',
		'Emma writes fantasy novels...',
		'emma.walker@example.com',
		'http://emmawalker.com',
		'Female',
		'http://emmawalker.com/pic20.jpg'
	);
