use literature;
INSERT INTO genres (genre_name)
VALUES ('Fiction'),
	('Non-Fiction'),
	('Mystery'),
	('Thriller'),
	('Science Fiction'),
	('Fantasy'),
	('Biography'),
	('Autobiography'),
	('Self-Help'),
	('Romance'),
	('Historical Fiction'),
	('Horror'),
	('Poetry'),
	('Drama'),
	('Adventure'),
	('Children\'s'),
	('Young Adult'),
	('Crime'),
	('Graphic Novel'),
	('Classic');
